version: 2.1
jobs:
  build:
    working_directory: ~/
    docker: # run the steps with Docker
      - image: circleci/node:8.17.0 
    steps:
      - run:
          name: Install Yarn 
          command: 'sudo npm install -g yarn'
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: # run build
          command: npm build